services:
  rails:
    build:
      args:
        user: roni
        uid: 1000
      context: .
      dockerfile: Dockerfile
    image: cadeaagua-rails
    container_name: cadeaagua-rails
    ports:
      - "3000:3000"
    restart: unless-stopped
    working_dir: /app
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://roni:${DB_PASSWORD}@postgres:5432/cadeaagua_development
    depends_on:
      - postgres
    networks:
      - cadeaagua

  postgres:
    image: postgres:14
    container_name: cadeaagua-postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: cadeaagua_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - cadeaagua

  pgadmin:
    image: dpage/pgadmin4
    container_name: cadeaagua-pgadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - postgres
    networks:
      - cadeaagua

volumes:
  postgres_data:

networks:
  cadeaagua:
    driver: bridge
